



export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored just  for You",
        description: 
        "Get interview questions and model answers based on your on your role, experience, and specific focus areas - no"
    },

    {
        id: "02",
        title: "Learn at your own pace",
        description: 
        "Expand answers only when you are ready. Dive deeper into any concept instatntly with AI-powered detailed "
        
    },
    {
        id: "03",
        title: "Capture Your insights",
        description: 
        " Add personal notes to any question and pin important ones to the top - making your learning more organize "
        
    },
    {
        id: "04",
        title: 'Understand the "why" Behind Answers  ',
        description: 
        " Beyond just answers - unlock detailed concept explainations generated by AI, helping you truly matter each "
        
    },
    {
        id: "05",
        title: "Save, Organize, and Revisit",
        descriptions: "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation "
    }
]